name: 'Check Runner Availability'
description: 'Check for availability of self-hosted GitHub runners and fallback to GitHub-hosted runners if needed'
author: '@mendesbarreto'
branding:
  icon: activity
  color: green
inputs:
  check-org-runners:
    description: 'If true it will look on the organization runners instead of repo runners'
    required: false
  github-token:
    description: 'GitHub token with repo and actions scope for querying runner information'
    required: true
  primary-runner:
    description: 'Comma-separated list of labels for the primary runner, e.g. self-hosted,linux'
    required: true
  fallback-runner:
    description: 'Name or labels of the fallback runner, e.g. ubuntu-latest'
    required: true
outputs:
  use-runner:
    description: 'The runner to use, either the primary or the fallback runner, based on availability'
runs:
  using: 'node20'
  main: 'dist/index.js'
